title: Epub Novels
logo: /assets/img/logo.png
description: A collection of ePub novels available for download.
show_downloads: true
google_analytics: 
baseurl: https://ashenara.github.io/ashepub 
theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-admin
  - jekyll-seo-tag