title: Arashe
logo: /assets/img/logo.png
description: ePub Light Novel
show_downloads: true
google_analytics: G-7HTQK96HMC
theme: jekyll-theme-minimal
domain: ashepub.netlify.app
url: https://ashepub.netlify.app/
baseurl: ""
plugins:
  - jekyll-sitemap